Update circleci, add local test script, put version numbers in circle-ci envvars.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,22 +3,44 @@ jobs:
   build:
     working_directory: /app
     docker:
-      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci
+      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci:0.0.4
     environment:
+      # Used for ECR
       AWS_DEFAULT_REGION: us-east-1
+      # ECR's
       ECR_ENDPOINT: 578681496768.dkr.ecr.us-east-1.amazonaws.com
+      # Bump these versions, and commit to master to upload a new version to ECR
+      NDAUNODE_CONTAINER_VERSION: 0.0.2
     steps:
-      - checkout
+      - run:
+          name: Transfer environment variables to files
+          command: |
+            # add ssh key to
+            mkdir -p /root/.ssh
+            echo -e "$gomu" > /root/.ssh/id_rsa
+            chmod 600 /root/.ssh/id_rsa
+
+            # install helm certs
+            mkdir -p /root/.helm
+            echo -e "$helm_ca_pem" > /root/.helm/ca.pem
+            echo -e "$helm_cert_pem" > /root/.helm/cert.pem
+            echo -e "$helm_key_pem" > /root/.helm/key.pem
+
+            # install kube config certs from environment variables
+            echo -e "$kube_config" > /root/kubeconfig
+      - run:
+          name: Checkout code
+          command: |
+            git clone $CIRCLE_REPOSITORY_URL -b $CIRCLE_BRANCH /app --depth=1
+            cp /root/.ssh/id_rsa /app/github_chaos_deploy
       - setup_remote_docker:
           docker_layer_caching: true
       - run:
           name: Build ndaunode-test image
           command: |
             # build ndaunode tests
-            echo -e "$gomu" > ssh-key
-            docker build -t ndaunode-test --build-arg SSH_KEY_FILE="ssh-key" . -f ./ndaunode-test.docker
+            docker build -t ndaunode-test . -f /app/ndaunode-test.docker
             # cleanup
-            rm ssh-key
             docker rmi ndaunode-test
       - run:
           name: AWS ECR Login
@@ -27,7 +49,6 @@ jobs:
       - run:
           name: Check ndaunode version on ECR
           command: |
-            source ./.circleci/build-versions.env
             # Compare this container version with ECR. Fail build if version already exists.
             version_check=$(aws ecr describe-images --repository-name ndaunode | jq ".imageDetails[].imageTags[]? | select (. == \"${NDAUNODE_CONTAINER_VERSION}\")")
             if [ ! -z "$version_check" ]; then
@@ -39,87 +60,53 @@ jobs:
             sha=${CIRCLE_SHA1: -7}
             sha_check=$(aws ecr describe-images --repository-name ndaunode | jq ".imageDetails[].imageTags[]? | select (. == \"${sha}\")")
             if [ ! -z "$sha_check" ]; then
-              echo "Chaosnode container version ${sha} already exists." | tee -a /tmp/pushlog
+              echo "Chaosnode container version ${sha} already exists." >&2
               exit 1
             fi
       - run:
           name: Build ndaunode
           command: |
             # build ndaunode with ssh key
-            echo -e "$gomu" > ssh-key
-            docker build -t ndaunode --build-arg SSH_KEY_FILE="ssh-key" .
-            # clean up
-            rm ssh-key
+            docker build -t ndaunode .
       - run:
           name: Push ndaunode
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              source ./.circleci/build-versions.env
+            if [ "${CIRCLE_BRANCH}" == "41-circle-ci-build-deploy" ]; then
               # Do not upload commit hash that already exists.
               # Should never really happen as long as master is not tampered with.
               commit_hash=${CIRCLE_SHA1: -7}
               commit_hash_check=$(aws ecr describe-images --repository-name ndaunode | jq ".imageDetails[].imageTags[]? | select (. == \"${commit_hash}\")")
               if [ ! -z "$commit_hash_check" ]; then
-                echo "Chaosnode container hash ${commit_hash} already exists. Will not push." > /tmp/pushlog
+                echo "Chaosnode container hash ${commit_hash} already exists. Will not push." >&2
               else
-                new_tag="${ECR_ENDPOINT}/ndaunode:${commit_hash}"
-                docker tag ndaunode $new_tag
-                docker tag ndaunode $NDAUNODE_CONTAINER_VERSION
-                docker push $new_tag
-                docker push $NDAUNODE_CONTAINER_VERSION
-                echo "Pushed ndaunode container hash ${commit_hash}." > /tmp/pushlog
+                commit_tag="${ECR_ENDPOINT}/ndaunode:${commit_hash}"
+                version_tag="${ECR_ENDPOINT}/ndaunode:${NDAUNODE_CONTAINER_VERSION}"
+                latest_tag="${ECR_ENDPOINT}/ndaunode:latest"
+
+                docker tag ndaunode $commit_tag
+                docker tag ndaunode $version_tag
+                docker tag ndaunode $latest_tag
+
+                docker push $commit_tag
+                docker push $version_tag
+                docker push $latest_tag
+
+                echo "Pushed ndaunode container hash ${commit_hash}." >&2
               fi
             fi
       - run:
           name: Install kubectl, helm, upgrade test net
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              # get version numbers
-              source ./.circleci/build-versions.env
+            if [ "${CIRCLE_BRANCH}" == "41-circle-ci-build-deploy" ]; then
 
-              # download kubectl and install it
-              curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl &&\
-              chmod +x ./kubectl &&\
-              sudo mv ./kubectl /usr/local/bin/kubectl
+              # Clone the k-os repo
+              GIT_SSH_COMMAND='ssh -i /root/.ssh/id_rsa' git clone git@github.com:oneiro-ndev/k-os.git -b use-dockerized-tendermint /root/k-os
 
-              # Use kube_config from environment variables
-              echo $kube_config > ./kubeconfig
-              export KUBECONFIG=./kubeconfig
+              # Remove old test net
+              KUBECONFIG=/root/kubeconfig helm del --purge mario luigi --tls || echo "mario and luigi could not be deleted" >&2
 
-              # download and install helm
-              curl https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz > helm.tgz
-              tar -zxvf helm.tgz
-              sudo mv linux-amd64/helm /usr/local/bin/helm
-
-              # clone the k-os repo
-              git clone git@github.com:oneiro-ndev/k-os.git
-
-              # install certs for helm
-              mkdir -p ~/.helm
-              echo -e "$helm_ca_pem" > ~/.helm/ca.pem
-              echo -e "$helm_cert_pem" > ~/.helm/cert.pem
-              echo -e "$helm_key_pem" > ~/.helm/key.pem
-
-              # use the dev-chaos cluster
-              kubectl config use-context dev-chaos.cluster.ndau.tech
-
-              # upgrade castor
-              helm upgrade ren k-os/helm/ndaunode \
-                --set ndaunode.image.tag=$NDAUNODE_CONTAINER_VERSION \
-                --reuse-values \
-                --recreate-pods \
-                --tls
-
-              # update pollux
-              helm upgrade stimpy k-os/helm/ndaunode \
-                --set ndaunode.image.tag=$NDAUNODE_CONTAINER_VERSION \
-                --reuse-values \
-                --recreate-pods \
-                --tls
+              # create new multinode test net
+              KUBECONFIG=/root/kubeconfig /root/k-os/env/aws/multinode/ndau.js 30500 mario luigi
 
             fi
-
-      # Save the push log
-      - store_artifacts:
-          path: /tmp/pushlog
 
